### ISSUE TITLE
CPU time not stored when larger than around 2^50

### ISSUE THREAD

**Issue by olorin** [WhereSoftwareGoesToDie/ceilometer-publisher-vaultaire#13]
I'm not sure why this number specifically; the highest value I have recorded is 737851720000000, but it's obviously going to break when we get to 2^64.

We can either wrap to zero when it gets bigger than a certain value and handle it the same way we do reboots, or we can switch to a cpu-time/time model like we do in [vaultaire-collector-pmacct](https://github.com/anchor/vaultaire-collector-pmacct) - maybe the time since last sample, I believe this is included in the Ceilometer messages?

Thoughts @oswynb @tranma @barneydesmond @glasnt @afcowie?

**Comment by oswynb** [comment]
2^64 cpuns ~= 584 cpuyears, I think we should be OK?

**Comment by barneydesmond** [comment]
737851720000000ns is roughly 8.5 days, are we sure this isn't just because we haven't had any longer-running instances?

I too am not concerned about hitting 2^64 nanoseconds. At least not any more concerned that DJB and his TAI64N.

**Comment by olorin** [comment]
Possibly, given it's stored by-core now, but it's still not being stored above 2^50.

**Comment by oswynb** [comment]
Ahh shoot, right. JSON. 52/53 bits precision max. Unsure what you mean by cpu-time/time model? Will check the time since last sample in the cpu metadata.

**Comment by oswynb** [comment]
Just checked, there's no last time. That is only for notifications, and cpu is pollster

**Comment by oswynb** [comment]
Could convert nano to micro? Pretty sure we're not actually getting things at nano-precision.

**Comment by olorin** [comment]
Yeah, false alarm, the bug is elsewhere.
