### ISSUE TITLE
event_type should be part of the identifier

### ISSUE THREAD

**Issue by oswynb** [WhereSoftwareGoesToDie/ceilometer-publisher-vaultaire#6]
Without this events which come in pairs will have the same address, and make it indistinguishable which is the start event, and which is the end event.

However for the consolidated output, this should be kept out of the address as the event-based information is rolled into the consolidated SimplePoint

**Comment by olorin** [comment]
@oswynb is this done?

**Comment by oswynb** [comment]
Yes, closing.
